version: "3.4"

x-defaults: &defaults
    restart: always

services:
    db:
        <<: *defaults
        image: "postgres:alpine"
        container_name: "cc_db"
        volumes:
            - cc_db:/var/lib/postgresql/data
        ports:
            - "${DATABASE_PORT:-5432}:5432"
    cache:
        <<: *defaults
        image: "redis:alpine"
        container_name: "cc_cache"
        ports:
            - "6379:6379"

volumes:
    cc_db: { }
